version: 2

sources:
   - name: raw
     schema: gz_raw_data # schema == dataset   
     
     tables:
       - name: product
         identifier: raw_gz_product
         description: products of Greenweez / we have purchase_price per each product_id row
         columns:
           - name: products_id
             description: date of purchase
             tests:
              - not_null
              - unique                            
           - name: purchse_price
             description: price of product
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         
         # Freshness testing - make sure to fill in the ...
         freshness:
           warn_after: {count: 1, period: minute}
           error_after: {count: 2400, period: day}
         loaded_at_field: CAST(date_date AS TIMESTAMP)

         tests:         
           - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - orders_id
                - pdt_id
              #quote_columns: true
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: order id
             tests:            
              - not_null  
           - name: pdt_id
             description: product id
             tests:            
              - not_null           
           - name: revenue
             description: revenue per order
           - name: quantity
             description: date of purchase
       - name: ship
         identifier: raw_gz_ship
         description: sales of Greenweez / we have costs rows per each orders_id
         columns:           
           - name: orders_id
             description: id of an order 
             tests:
              - not_null
              - unique
           - name: shipping_fee
             description: date of purchase
           - name: logcost
             description: date of purchase
           - name: ship_cost
             description: date of purchase