version: 2

sources:
   - name: raw
     schema: gz_raw_data # schema == dataset
     tables:
       - name: product
         identifier: raw_gz_product
       - name: sales
         identifier: raw_gz_sales
       - name: ship
         identifier: raw_gz_ship